name: Testing Server
main: me.hgilman.TestingServer.TestingServer
version: 1.0

commands:
   signalstop:
      description: Stops the server with warnings first.
      usage: |
           /signalstop
   giverequirements:
      description: Gives the user the requirements for a spell.
      usage: |
           /giverequirements <spell>